version: '3'

services:
    laudo-php82:
      container_name: "app-php"
      build:
        context: ./
        dockerfile: ./docker/Dockerfile
        args:
          APP_PORT: '80'
          ODBC_DRIVER_SCRIPT: './docker/install_ODBC_Driver.sh'
          OPENSSL_UPDATER: './docker/install_openssl.sh'
      ports:
        - '${APP_PORT:-80}:80'
        - "1433:1433/TCP"
      volumes:
        - './laudo:/var/www/html'