version: '3'

services:

    php82:
      container_name: "testing-image-php82"
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - '${APP_PORT:-80}:80'
      volumes:
        - '.:/var/www/html'
